### ISSUE TITLE
Update READMY

### ISSUE THREAD

**Issue by Artem100** [Artem100/homepage#21]
Add small description:
- General info;
- Technologies;
- To look the site.

**Comment by Ary20021** [comment]
# Resume for Ryu Hoshi
 
## General info
The main goal of project - create resume for street fighter **Ryu Hoshi**. He decided to downshift martial arts career and get into IT.

## Technologies
* HTML;
* CSS;

## Link website on resume of Ryu Hoshi
URL: https://artem100.github.io/homepage/
